### ISSUE TITLE
Can't apply theme

### ISSUE THREAD

**Issue by LordWorm1996** [project-gauntlet/gauntlet#74]
mode = "dark"

background = [
    { color = "#ff0e82", alpha = 0.3 },
    { color = "#c79bff", alpha = 0.5 },
    "#19002E",
    "#240041"
]

text = [
    "#f8f8f2",
    "#ff0e82",
    "#c79bff",
    "#131411"
]

[window.border]
border_radius = 10
border_width = 2
border_color = { color = "#ff0e82", alpha = 0.5 }

[content.border]
border_radius = 4

this is my theme, yet whenever I restart the application it doesn't get applied

**Comment by Exidex** [comment]
border fields do not have the `border_` prefix:
```toml
[window.border]
radius = 10
width = 2
color = { color = "#ff0e82", alpha = 0.5 }

[content.border]
radius = 4
````
